In [14]:
import pandas as pd
import numpy as np
data_dir = "/orcd/pool/003/dbertsim_shared/ukb/cancer_risk/"

In [8]:
cohort = "test"
df = pd.read_csv(f"{data_dir}../ukb_cancer_{cohort}_female.csv")

In [9]:
df = df.loc[df['lung_cancer'] == 0]

In [15]:
df_cox = pd.read_csv(f"{data_dir}cox/lung_cancer_cox_risk_{cohort}.csv")
df_ord = pd.read_csv(f"{data_dir}ordinal/lung_cancer_{cohort}.csv")
df_xgb = pd.read_csv(f"{data_dir}xgb/lung_cancer_xgb_risk_{cohort}.csv")

In [19]:
df_ord.iloc[100:150,:]

         eid  prob_0.5yr  prob_1yr  prob_2yr  prob_5yr  prob_10yr  prob_100yr
100  1248513    0.500001  0.500002  0.500003  0.500005   0.500009    0.500016
101  1252319    0.500001  0.500002  0.500005  0.500006   0.500009    0.500021
102  1256655    0.500001  0.500002  0.500003  0.500005   0.500007    0.500013
103  1256715    0.500001  0.500002  0.500003  0.500005   0.500008    0.500015
104  1266558    0.500001  0.500002  0.500008  0.500018   0.500119    0.500168
105  1268707    0.500001  0.500002  0.500003  0.500004   0.500005    0.500007
106  1271406    0.500001  0.500002  0.500004  0.500026   0.500050    0.500071
107  1277043    0.500001  0.500002  0.500004  0.500005   0.500007    0.500010
108  1284836    0.500001  0.500002  0.500003  0.500006   0.500011    0.500021
109  1290293    0.500001  0.500002  0.500006  0.500008   0.500015    0.500019
110  1291542    0.500001  0.500002  0.500003  0.500005   0.500006    0.500007
111  1293110    0.500001  0.500002  0.500003  0.500005   0.500009    0.500016
112  1297689    0.500001  0.500002  0.500003  0.500004   0.500007    0.500009
113  1301021    0.500001  0.500003  0.500006  0.500011   0.500023    0.500044
114  1301778    0.500001  0.500002  0.500004  0.500008   0.500014    0.500025
115  1308270    0.500001  0.500002  0.500003  0.500005   0.500006    0.500008
116  1309607    0.500001  0.500002  0.500003  0.500005   0.500006    0.500008
117  1315702    0.500001  0.500002  0.500005  0.500007   0.500009    0.500012
118  1316417    0.500001  0.500002  0.500003  0.500005   0.500007    0.500011
119  1317937    0.500001  0.500003  0.500005  0.500007   0.500014    0.500027
120  1320529    0.500001  0.500002  0.500003  0.500004   0.500005    0.500006
121  1322341    0.500001  0.500003  0.500004  0.500005   0.500008    0.500012
122  1326097    0.500001  0.500002  0.500003  0.500005   0.500008    0.500013
123  1326643    0.500001  0.500002  0.500003  0.500005   0.500008    0.500015
124  1329153    0.500001  0.500002  0.500004  0.500007   0.500009    0.500013
125  1336208    0.500001  0.500002  0.500003  0.500005   0.500009    0.500016
126  1338475    0.500001  0.500002  0.500003  0.500004   0.500006    0.500009
127  1339146    0.500001  0.500002  0.500003  0.500005   0.500009    0.500014
128  1340134    0.500001  0.500002  0.500003  0.500004   0.500005    0.500007
129  1345006    0.500001  0.500002  0.500003  0.500004   0.500006    0.500008
130  1348387    0.500001  0.500002  0.500003  0.500004   0.500007    0.500009
131  1350512    0.500001  0.500004  0.500010  0.500016   0.500038    0.500066
132  1353827    0.500001  0.500002  0.500003  0.500006   0.500013    0.500030
133  1359269    0.500001  0.500002  0.500004  0.500006   0.500008    0.500011
134  1361463    0.500001  0.500003  0.500004  0.500006   0.500009    0.500011
135  1361678    0.500001  0.500002  0.500003  0.500005   0.500008    0.500014
136  1361818    0.500001  0.500002  0.500003  0.500005   0.500006    0.500007
137  1361891    0.500001  0.500002  0.500003  0.500005   0.500006    0.500007
138  1364685    0.500001  0.500002  0.500003  0.500004   0.500005    0.500007
139  1365336    0.500001  0.500002  0.500003  0.500004   0.500005    0.500007
140  1376678    0.500001  0.500002  0.500004  0.500006   0.500010    0.500021
141  1378970    0.500001  0.500002  0.500004  0.500005   0.500007    0.500010
142  1378988    0.500001  0.500002  0.500005  0.500007   0.500020    0.500031
143  1379877    0.500001  0.500002  0.500004  0.500005   0.500007    0.500009
144  1379976    0.500001  0.500002  0.500003  0.500006   0.500013    0.500031
145  1380759    0.500001  0.500002  0.500003  0.500004   0.500005    0.500007
146  1383481    0.500001  0.500002  0.500003  0.500004   0.500005    0.500007
147  1384285    0.500001  0.500003  0.500004  0.500009   0.500015    0.500062
148  1391176    0.500001  0.500002  0.500005  0.500016   0.500025    0.500057
149  1398184    0.500001  0.500002  0.500003  0.500005   0.500007    0.500009

In [16]:
df_cox

           eid      risk  risk_1years  risk_2years  risk_5years  risk_10years
0      1001803 -1.765629     0.000016     0.000040     0.000124      0.000287
1      1002917  0.319032     0.000245     0.000608     0.001862      0.004305
2      1004330 -0.945279     0.000047     0.000118     0.000360      0.000834
3      1006889  0.672473     0.000388     0.000963     0.002946      0.006807
4      1007241  1.366514     0.000956     0.002372     0.007247      0.016697
...        ...       ...          ...          ...          ...           ...
10506  6017956  0.674816     0.000389     0.000966     0.002955      0.006828
10507  6018670 -0.754705     0.000061     0.000151     0.000461      0.001068
10508  6018723 -1.492461     0.000023     0.000058     0.000177      0.000409
10509  6019085 -2.286681     0.000008     0.000021     0.000063      0.000146
10510  6020560 -0.680405     0.000067     0.000166     0.000508      0.001176

[10511 rows x 6 columns]

In [18]:
df_xgb

,eid,risk_0years,risk_1years,risk_2years,risk_5years,risk_10years
0,1001803,0.000348,0.000245,0.000462,0.001448,0.003548
1,1002917,0.000447,0.000267,0.000531,0.002383,0.038615
2,1004330,0.000354,0.000263,0.000517,0.001558,0.003504
3,1006889,0.000359,0.000198,0.000627,0.001482,0.003608
4,1007241,0.001437,0.000769,0.000832,0.002764,0.004143
...,...,...,...,...,...,...
10515,6017956,0.001439,0.000329,0.000605,0.001947,0.007045
10516,6018670,0.000449,0.000210,0.000502,0.001519,0.003446
10517,6018723,0.000446,0.000238,0.000528,0.001555,0.003427
10518,6019085,0.000485,0.000279,0.000569,0.001662,0.003484
10519,6020560,0.000514,0.000249,0.000485,0.001730,0.003594

In [27]:
df_cox = pd.read_csv(f"{data_dir}cox/acute_kidney_injury_cox_risk_{cohort}.csv")
df_cox

          eid      risk  risk_1years  risk_2years  risk_5years  risk_10years
0     1005250 -0.098798     0.000391     0.001160     0.004321      0.017856
1     1013385  0.098222     0.000478     0.001416     0.005273      0.021755
2     1016689 -0.323530     0.000312     0.000924     0.003444      0.014248
3     1020306 -0.115836     0.000385     0.001141     0.004248      0.017553
4     1033770  0.452182     0.000684     0.002026     0.007537      0.030984
...       ...       ...          ...          ...          ...           ...
5832  6009161  1.137888     0.001368     0.004053     0.015033      0.061072
5833  6010603  0.394554     0.000645     0.001912     0.007111      0.029254
5834  6014844 -1.364928     0.000109     0.000322     0.001201      0.004988
5835  6016558  0.997815     0.001188     0.003518     0.013058      0.053216
5836  6019274 -1.379160     0.000107     0.000318     0.001184      0.004917

[5837 rows x 6 columns]

In [24]:
df_ord

          eid  prob_1yr  prob_2yr  prob_5yr  prob_10yr  prob_100yr
0     1005250  0.500004  0.500008  0.500012   0.500021    0.500036
1     1013385  0.500004  0.500008  0.500012   0.500021    0.500037
2     1016689  0.500004  0.500009  0.500014   0.500023    0.500043
3     1020306  0.500004  0.500008  0.500012   0.500023    0.500042
4     1033770  0.500004  0.500009  0.500013   0.500023    0.500051
...       ...       ...       ...       ...        ...         ...
4727  5988317  0.500004  0.500008  0.500013   0.500021    0.500036
4728  6010603  0.500004  0.500008  0.500013   0.500026    0.500097
4729  6014844  0.500004  0.500008  0.500012   0.500020    0.500035
4730  6016558  0.500004  0.500008  0.500014   0.500047    0.502512
4731  6019274  0.500004  0.500008  0.500012   0.500020    0.500035

[4732 rows x 6 columns]

In [16]:
df_xgb = pd.read_csv(f"{data_dir}xgb/acute_kidney_injury_xgb_risk_{cohort}.csv")
df_m3h = pd.read_csv(f"{data_dir}m3h/acute_kidney_injury_{cohort}.csv")
df_cox = pd.read_csv(f"{data_dir}cox/acute_kidney_injury_cox_risk_{cohort}.csv")

In [20]:
df_xgb.loc[df_xgb['eid'].isin([1152453,5592634,1113732])]

,eid,risk_0years,risk_1years,risk_2years,risk_5years,risk_10years
1156,1152453,0.001225,0.000841,0.002835,0.023554,0.143661
4629,5592634,0.003700,0.000690,0.004257,0.012647,0.079883
4757,1113732,0.003157,0.000507,0.001844,0.008669,0.041089

In [43]:
df_cox

           eid      risk  risk_1years  risk_2years  risk_5years  risk_10years
0      1000380 -0.146739     0.000379     0.001123     0.004183      0.017286
1      1001803 -2.322742     0.000042     0.000125     0.000467      0.001943
2      1002917  0.205037     0.000540     0.001601     0.005957      0.024551
3      1003287  0.655433     0.000850     0.002519     0.009364      0.038383
4      1003776 -0.154640     0.000376     0.001114     0.004149      0.017150
...        ...       ...          ...          ...          ...           ...
13986  6016461 -0.312289     0.000321     0.000951     0.003541      0.014649
13987  6018670 -1.129118     0.000141     0.000417     0.001556      0.006458
13988  6018796 -1.384358     0.000109     0.000323     0.001203      0.004996
13989  6020560 -0.482048     0.000270     0.000801     0.002985      0.012360
13990  6021070 -1.200018     0.000131     0.000389     0.001449      0.006014

[13991 rows x 6 columns]

In [51]:
df_cox[df_cox.isna().any(axis=1)]

Empty DataFrame
Columns: [eid, risk, risk_1years, risk_2years, risk_5years, risk_10years]
Index: []

In [54]:
df_cox.loc[df_cox['eid']==5970892]

             eid  risk  risk_1years  risk_2years  risk_5years  risk_10years
13959  5970892.0   NaN          NaN          NaN          NaN           NaN

In [15]:
df_xgb.loc[df_xgb['eid'].isin([5983175, 5983430.0])]

,eid,risk_0years,risk_1years,risk_2years,risk_5years,risk_10years
13991,5983175,0.001885,0.000499,0.012012,0.030927,0.096831
13992,5983430,0.000894,0.000987,0.001608,0.005207,0.023379

In [21]:
df_cox = df_cox.dropna(subset=['eid'])
eids = set(df_cox[df_cox.isna().any(axis=1)]['eid'])

In [24]:
temp=df.loc[df['eid'].isin(eids)]
olink_cols = [c for c in df.columns if c.startswith("olink")]
temp[olink_cols].isna().mean(axis=1)

13991    0.063356
13992    0.003082
13993    0.001712
13994    0.003425
13995    0.000342
13996    0.032192
13997    0.000342
13998    0.006164
13999    0.540411
14000    0.000685
14001    0.537329
14002    0.001027
14003    0.001370
14004    0.040753
14005    0.000342
14006    0.001027
14007    0.003082
14008    0.004452
14009    0.000000
14010    0.000342
14011    0.026027
14012    0.000000
14013    0.191438
14014    0.000685
14015    0.499658
14016    0.001712
14017    0.003082
14018    0.000685
14019    0.000685
14020    0.017466
14021    0.002397
14022    0.000000
dtype: float64

In [124]:
df_m3h

           eid  prob_1yr  prob_2yr  prob_5yr  prob_10yr  prob_100yr
0      1003828  0.481672  0.477573  0.124045   0.188948    0.453234
1      1006889  0.490048  0.489733  0.124661   0.185725    0.449320
2      1007988  0.486204  0.484809  0.122790   0.180427    0.435367
3      1009427  0.485040  0.492334  0.123083   0.181221    0.435954
4      1010774  0.486201  0.490045  0.122863   0.181723    0.440119
...        ...       ...       ...       ...        ...         ...
11586  6017829  0.490638  0.492138  0.123352   0.183222    0.441366
11587  6018723  0.475941  0.493640  0.124918   0.186384    0.443703
11588  6019085  0.488880  0.489816  0.124746   0.183256    0.441534
11589  6019370  0.490642  0.493668  0.122773   0.185245    0.450574
11590  6020293  0.490637  0.493499  0.123346   0.188442    0.460367

[11591 rows x 6 columns]

In [105]:
eids_m3h = set(df_m3h['eid']) 
eids_xgb = set(df_xgb['eid'])
eids_cox = set(df_cox['eid'])
eids = set(df['eid'])

In [106]:
assert len(eids.intersection(eids_xgb)) == len(eids)
len(eids)

13991

In [107]:
len(eids_m3h)

11591

In [111]:
eids_intersect = eids.intersection(eids_m3h)

In [98]:
assert len(eids.intersection(eids_cox)) == len(eids)
len(eids.intersection(eids_cox))

AssertionError:

In [99]:
len(eids.intersection(eids_cox))

0

In [116]:
temp = df.loc[df['eid'].isin(eids_intersect)][['acute_kidney_injury', 'acute_kidney_injury_time_to_diagnosis']]